###Get a list of all users
GET http://localhost:3000/user

### GET a user by id
GET http://localhost:3000/user/601cdd6cef46df3190cfdf4c

### Create a users
POST http://localhost:3000/user
Content-Type: application/json

{
    "name" : "test user",
    "email":"test@gmail.com",
    "phone":"1234567891",
    "password":"1234"
}

### Update a users by id
PATCH  http://localhost:3000/user/601e75b19c786b0ca035be5f
Content-Type: application/json

{
   "name" : "test user update"
}


### Delete a user by id
DELETE  http://localhost:3000/user/601e75b19c786b0ca035be5f

### 404 route Not Found
GET http://localhost:3000/abc_xyz